name: After Push Action

on:
  push:
    branches:
      - main
    
jobs:
  format-test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: "Format Code"
        run: bun run format
      - name: "Test App"
        run: bun run test
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply formatting changes
  build-run:
    needs: format-test
    runs-on: ubuntu-latest
    env:
      DOCKER_PORT: 3000
      ANOTHER_ENV_VAR: 3001
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run Docker Compose services
      run: docker-compose up --build
