name: After Push Action

on:
  push:
    branches:
      - main
    
jobs:
  format-test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: "Format Code"
        run: bun run format
      - name: "Test App"
        run: bun run test
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply formatting changes
  build-run:
    needs: format-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Create fake .env file
      run: |
        echo "DOCKER_PORT=3000" > .env
        echo "DOCKER_PRISMA_PORT=3001" >> .env
        echo "SENTRY_DSN=" >> .env
      shell: bash
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Docker Compose services
      run: docker-compose build
