name: Fix And Test

on:
  push:
    branches:
      - main
    
jobs:
  format-test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: "Format Code"
        run: bun run format
      - name: "Test App"
        run: bun run test
